# Generated by Django 4.1.7 on 2023-03-26 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Это название пункта меню', max_length=50)),
                ('url', models.CharField(blank=True, help_text='URL-адрес, на который будет перенаправлен пользователь при нажатии на пункт меню.\nОн может быть пустым, если вместо URL используется именованный URL.', max_length=100, null=True)),
                ('named_url', models.CharField(blank=True, help_text='Именованный URL, на который будет перенаправлен пользователь при нажатии на пункт меню. \nОн может быть пустым, если вместо него используется обычный URL.', max_length=50, null=True)),
                ('menu_name', models.CharField(help_text='это имя меню, к которому относится данный пункт. \nЭто позволяет иметь несколько меню на сайте и использовать их на разных страницах.', max_length=50)),
                ('parent', models.ForeignKey(blank=True, help_text='Поле указывает на родительский пункт меню. Если значение этого поля пустое, то это означает, \nчто этот пункт меню является корневым элементом.', null=True, on_delete=django.db.models.deletion.CASCADE, to='menuapp.menuitem')),
            ],
        ),
    ]
